name: Build zip

on:
  push:
    branches:
      - main

jobs:

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          artifacts: build


 build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."
          zip -r build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip
